version: '3'

services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress_password
      - WORDPRESS_DB_NAME=wordpress
    # Add these lines for PHP configuration
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - db
    networks:
      - cyberex

  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress_password
    networks:
      - cyberex

volumes:
  db_data:

networks:
  cyberex: